export type Word = {
  letters: (string | null)[];
  frequency: number;
};

export const WORDS: Word[] = [
  { letters: [null, "A", null, "E"], frequency: 119 },
  { letters: [null, "I", null, "E"], frequency: 91 },
  { letters: [null, "O", null, "E"], frequency: 91 },
  { letters: [null, "A", "R", null], frequency: 71 },
  { letters: [null, "E", "A", null], frequency: 64 },
  { letters: [null, "E", null, "T"], frequency: 64 },
  { letters: [null, "I", "N", null], frequency: 63 },
  { letters: [null, "O", "O", null], frequency: 62 },
  { letters: [null, "E", "E", null], frequency: 59 },
  { letters: [null, "O", "R", null], frequency: 58 },
  { letters: [null, "O", "L", null], frequency: 53 },
  { letters: [null, null, "C", "K"], frequency: 52 },
  { letters: [null, null, "R", "E"], frequency: 51 },
  { letters: [null, "O", null, "T"], frequency: 51 },
  { letters: ["C", "O", null, null], frequency: 51 },
  { letters: [null, null, "L", "L"], frequency: 50 },
  { letters: [null, "A", "N", null], frequency: 49 },
  { letters: ["S", null, "A", null], frequency: 48 },
  { letters: [null, "I", "L", null], frequency: 47 },
  { letters: [null, null, "S", "T"], frequency: 46 },
  { letters: [null, "A", "I", null], frequency: 45 },
  { letters: [null, "U", null, "E"], frequency: 45 },
  { letters: ["T", "O", null, null], frequency: 45 },
  { letters: [null, "A", "L", null], frequency: 45 },
  { letters: [null, "A", "S", null], frequency: 43 },
  { letters: [null, null, "N", "E"], frequency: 43 },
  { letters: [null, null, "L", "E"], frequency: 43 },
  { letters: [null, "A", null, "T"], frequency: 42 },
  { letters: [null, "U", "R", null], frequency: 42 },
  { letters: ["B", "A", null, null], frequency: 41 },
  { letters: ["L", "O", null, null], frequency: 41 },
  { letters: [null, "A", null, "K"], frequency: 40 },
  { letters: [null, "E", "R", null], frequency: 39 },
  { letters: ["B", "O", null, null], frequency: 39 },
  { letters: [null, "A", null, "L"], frequency: 38 },
  { letters: [null, null, "A", "T"], frequency: 37 },
  { letters: ["W", "A", null, null], frequency: 37 },
  { letters: [null, "O", null, "Y"], frequency: 37 },
  { letters: ["H", "A", null, null], frequency: 36 },
  { letters: ["M", "A", null, null], frequency: 36 },
  { letters: [null, "E", null, "L"], frequency: 36 },
  { letters: [null, null, "T", "E"], frequency: 36 },
  { letters: [null, "I", null, "T"], frequency: 36 },
  { letters: [null, null, "K", "E"], frequency: 35 },
  { letters: ["S", "O", null, null], frequency: 35 },
  { letters: [null, null, "N", "G"], frequency: 35 },
  { letters: [null, "O", "N", null], frequency: 35 },
  { letters: ["S", null, null, "T"], frequency: 35 },
  { letters: [null, "U", "N", null], frequency: 35 },
  { letters: [null, "R", "A", null], frequency: 35 },
  { letters: [null, "U", "S", null], frequency: 34 },
  { letters: [null, null, "N", "T"], frequency: 34 },
  { letters: ["T", "A", null, null], frequency: 34 },
  { letters: ["D", "O", null, null], frequency: 34 },
  { letters: [null, "L", "A", null], frequency: 34 },
  { letters: ["D", null, null, "E"], frequency: 34 },
  { letters: [null, "O", null, "L"], frequency: 34 },
  { letters: ["M", "O", null, null], frequency: 33 },
  { letters: [null, null, "M", "E"], frequency: 33 },
  { letters: [null, "E", "L", null], frequency: 33 },
  { letters: [null, "E", null, "D"], frequency: 33 },
  { letters: [null, "O", null, "K"], frequency: 33 },
  { letters: ["P", "A", null, null], frequency: 33 },
  { letters: [null, "E", "N", null], frequency: 33 },
  { letters: ["P", "O", null, null], frequency: 33 },
  { letters: ["R", "A", null, null], frequency: 33 },
  { letters: ["L", null, null, "E"], frequency: 32 },
  { letters: [null, null, "A", "R"], frequency: 32 },
  { letters: [null, "O", null, "N"], frequency: 32 },
  { letters: ["L", "A", null, null], frequency: 32 },
  { letters: [null, null, "I", "N"], frequency: 32 },
  { letters: [null, null, "S", "H"], frequency: 32 },
  { letters: [null, "O", null, "A"], frequency: 32 },
  { letters: ["L", "I", null, null], frequency: 31 },
  { letters: ["M", null, null, "E"], frequency: 31 },
  { letters: ["S", null, null, "E"], frequency: 31 },
  { letters: [null, "O", null, "D"], frequency: 31 },
  { letters: ["C", "A", null, null], frequency: 31 },
  { letters: [null, null, "N", "K"], frequency: 31 },
  { letters: ["R", null, null, "E"], frequency: 31 },
  { letters: [null, null, null, "E", "R"], frequency: 270 },
  { letters: [null, "A", null, "E", null], frequency: 158 },
  { letters: [null, "A", null, null, "Y"], frequency: 135 },
  { letters: [null, "O", null, null, "Y"], frequency: 133 },
  { letters: [null, "O", null, "E", null], frequency: 115 },
  { letters: [null, null, "A", null, "E"], frequency: 114 },
  { letters: ["S", null, "A", null, null], frequency: 114 },
  { letters: [null, "I", null, "E", null], frequency: 112 },
  { letters: [null, null, null, "E", "D"], frequency: 112 },
  { letters: ["S", null, null, null, "E"], frequency: 109 },
  { letters: [null, null, "I", null, "E"], frequency: 106 },
  { letters: [null, "U", null, null, "Y"], frequency: 101 },
  { letters: ["S", "T", null, null, null], frequency: 96 },
  { letters: [null, "E", null, null, "Y"], frequency: 96 },
  { letters: [null, "R", "A", null, null], frequency: 94 },
  { letters: [null, "A", null, null, "R"], frequency: 93 },
  { letters: ["S", null, "O", null, null], frequency: 90 },
  { letters: [null, null, null, "A", "L"], frequency: 90 },
  { letters: [null, null, "O", null, "E"], frequency: 89 },
  { letters: [null, "R", "O", null, null], frequency: 89 },
  { letters: [null, null, null, "C", "H"], frequency: 86 },
  { letters: ["S", null, "I", null, null], frequency: 85 },
  { letters: [null, "A", null, null, "E"], frequency: 85 },
  { letters: [null, "R", null, null, "E"], frequency: 85 },
  { letters: [null, null, null, "S", "E"], frequency: 84 },
  { letters: [null, "I", null, null, "Y"], frequency: 82 },
  { letters: [null, null, "I", "N", null], frequency: 80 },
  { letters: [null, null, null, "L", "Y"], frequency: 80 },
  { letters: [null, null, null, "T", "Y"], frequency: 78 },
  { letters: [null, "R", "I", null, null], frequency: 78 },
  { letters: [null, "O", null, null, "E"], frequency: 77 },
  { letters: [null, "L", "A", null, null], frequency: 76 },
  { letters: [null, "A", "R", null, null], frequency: 76 },
  { letters: ["C", "O", null, null, null], frequency: 75 },
  { letters: [null, null, "R", null, "Y"], frequency: 73 },
  { letters: [null, "O", "R", null, null], frequency: 71 },
  { letters: [null, null, null, "L", "E"], frequency: 70 },
  { letters: [null, "A", "N", null, null], frequency: 70 },
  { letters: [null, null, "A", "R", null], frequency: 69 },
  { letters: ["S", "H", null, null, null], frequency: 69 },
  { letters: [null, "I", "N", null, null], frequency: 68 },
  { letters: ["C", "H", null, null, null], frequency: 68 },
  { letters: ["S", "P", null, null, null], frequency: 68 },
  { letters: ["S", null, null, "R", null], frequency: 67 },
  { letters: ["S", null, "E", null, null], frequency: 66 },
  { letters: [null, "O", "U", null, null], frequency: 65 },
  { letters: [null, null, "N", null, "Y"], frequency: 65 },
  { letters: ["S", null, null, "E", null], frequency: 65 },
  { letters: [null, "I", null, null, "R"], frequency: 65 },
  { letters: [null, null, "L", null, "Y"], frequency: 65 },
  { letters: [null, "A", null, "I", null], frequency: 64 },
  { letters: ["S", null, null, null, "Y"], frequency: 63 },
  { letters: [null, "U", "R", null, null], frequency: 63 },
  { letters: [null, null, "A", "N", null], frequency: 62 },
  { letters: ["C", "A", null, null, null], frequency: 62 },
  { letters: [null, "E", null, null, "E"], frequency: 62 },
  { letters: [null, null, null, "K", "Y"], frequency: 61 },
  { letters: [null, null, "R", null, "E"], frequency: 60 },
  { letters: [null, "O", null, null, "R"], frequency: 60 },
  { letters: ["M", "A", null, null, null], frequency: 60 },
  { letters: ["R", "E", null, null, null], frequency: 60 },
  { letters: [null, null, "U", null, "E"], frequency: 59 },
  { letters: ["P", "A", null, null, null], frequency: 59 },
  { letters: [null, "A", "L", null, null], frequency: 59 },
  { letters: [null, "E", "R", null, null], frequency: 59 },
  { letters: [null, null, null, "R", "Y"], frequency: 58 },
  { letters: [null, "H", "A", null, null], frequency: 58 },
  { letters: ["C", null, null, null, "E"], frequency: 58 },
  { letters: [null, null, "T", "E", null], frequency: 57 },
  { letters: [null, null, null, "T", "E"], frequency: 57 },
  { letters: [null, null, null, "I", "N"], frequency: 57 },
  { letters: [null, null, null, "C", "K"], frequency: 57 },
  { letters: [null, "E", "A", null, null], frequency: 57 },
  { letters: [null, null, null, "E", "L"], frequency: 57 },
  { letters: ["A", null, null, null, "E"], frequency: 57 },
  { letters: ["S", null, null, "L", null], frequency: 56 },
  { letters: ["S", null, null, null, "T"], frequency: 56 },
  { letters: [null, "A", "T", null, null], frequency: 56 },
  { letters: ["P", null, null, null, "Y"], frequency: 56 },
  { letters: ["C", null, null, "E", null], frequency: 56 },
  { letters: [null, null, null, null, "E", "R"], frequency: 874 },
  { letters: [null, "A", null, null, "E", null], frequency: 403 },
  { letters: [null, null, null, null, "E", "D"], frequency: 382 },
  { letters: [null, "O", null, null, "E", null], frequency: 323 },
  { letters: [null, null, null, null, "L", "E"], frequency: 280 },
  { letters: [null, "E", null, null, "E", null], frequency: 267 },
  { letters: [null, null, null, "T", "E", null], frequency: 256 },
  { letters: [null, "I", null, null, "E", null], frequency: 244 },
  { letters: [null, null, null, "I", "N", null], frequency: 235 },
  { letters: [null, "A", null, null, null, "R"], frequency: 226 },
  { letters: ["S", null, null, null, "E", null], frequency: 216 },
  { letters: [null, "U", null, null, "E", null], frequency: 215 },
  { letters: [null, null, null, null, "L", "Y"], frequency: 205 },
  { letters: [null, null, "N", null, "E", null], frequency: 196 },
  { letters: [null, null, "A", null, "E", null], frequency: 196 },
  { letters: ["R", "E", null, null, null, null], frequency: 195 },
  { letters: [null, null, null, "L", "E", null], frequency: 194 },
  { letters: [null, "A", "R", null, null, null], frequency: 190 },
  { letters: [null, "O", null, null, null, "R"], frequency: 189 },
  { letters: [null, null, "R", null, "E", null], frequency: 188 },
  { letters: [null, null, null, "T", null, "R"], frequency: 186 },
  { letters: [null, "E", null, null, null, "E"], frequency: 175 },
  { letters: [null, null, null, null, "N", "G"], frequency: 173 },
  { letters: [null, null, null, "I", null, "E"], frequency: 173 },
  { letters: [null, "E", null, null, null, "R"], frequency: 167 },
  { letters: [null, null, null, "A", null, "E"], frequency: 164 },
  { letters: [null, null, null, "K", "E", null], frequency: 162 },
  { letters: ["B", null, null, null, "E", null], frequency: 160 },
  { letters: [null, null, "L", null, "E", null], frequency: 160 },
  { letters: [null, "A", null, "I", null, null], frequency: 158 },
  { letters: [null, null, null, "D", "E", null], frequency: 158 },
  { letters: ["C", null, null, null, "E", null], frequency: 156 },
  { letters: [null, null, null, "I", null, "G"], frequency: 153 },
  { letters: [null, null, null, null, "A", "L"], frequency: 152 },
  { letters: [null, null, null, null, "E", "T"], frequency: 150 },
  { letters: [null, "A", "N", null, null, null], frequency: 149 },
  { letters: ["C", "O", null, null, null, null], frequency: 148 },
  { letters: [null, "O", null, null, null, "E"], frequency: 143 },
  { letters: [null, "A", null, null, null, "E"], frequency: 142 },
  { letters: ["C", "A", null, null, null, null], frequency: 139 },
  { letters: ["S", null, null, null, null, "Y"], frequency: 139 },
  { letters: [null, null, null, null, "O", "N"], frequency: 138 },
  { letters: [null, "I", null, null, null, "R"], frequency: 138 },
  { letters: ["P", null, null, null, "E", null], frequency: 138 },
  { letters: [null, null, "S", null, "E", null], frequency: 137 },
  { letters: [null, null, "N", null, null, "R"], frequency: 128 },
  { letters: [null, "E", null, "T", null, null], frequency: 127 },
  { letters: [null, "U", null, null, null, "R"], frequency: 125 },
  { letters: [null, null, null, "P", "E", null], frequency: 125 },
  { letters: [null, "I", "N", null, null, null], frequency: 123 },
  { letters: ["S", null, null, null, null, "E"], frequency: 122 },
  { letters: [null, null, null, null, "E", "N"], frequency: 122 },
  { letters: [null, null, "L", "L", null, null], frequency: 122 },
  { letters: [null, "O", "R", null, null, null], frequency: 120 },
  { letters: [null, "A", "L", null, null, null], frequency: 120 },
  { letters: [null, "A", null, "T", null, null], frequency: 118 },
  { letters: [null, "A", null, null, null, "N"], frequency: 117 },
  { letters: ["M", "A", null, null, null, null], frequency: 115 },
  { letters: ["S", "T", null, null, null, null], frequency: 115 },
  { letters: ["S", null, null, null, null, "R"], frequency: 115 },
  { letters: [null, null, "R", "I", null, null], frequency: 114 },
  { letters: [null, null, null, "G", "E", null], frequency: 114 },
  { letters: [null, null, null, "N", "E", null], frequency: 114 },
  { letters: [null, null, "O", null, "E", null], frequency: 113 },
  { letters: [null, null, "T", null, "E", null], frequency: 112 },
  { letters: [null, "I", null, null, null, "E"], frequency: 112 },
  { letters: ["S", null, "A", null, null, null], frequency: 111 },
  { letters: [null, "E", "A", null, null, null], frequency: 110 },
  { letters: [null, null, "I", null, "E", null], frequency: 110 },
  { letters: ["D", "E", null, null, null, null], frequency: 110 },
  { letters: ["L", null, null, null, "E", null], frequency: 110 },
  { letters: [null, "A", null, null, "L", null], frequency: 109 },
  { letters: [null, "O", null, "I", null, null], frequency: 109 },
  { letters: [null, null, null, "E", null, "T"], frequency: 109 },
  { letters: [null, null, "A", null, null, "R"], frequency: 109 },
  { letters: ["S", null, "R", null, null, null], frequency: 108 },
  { letters: ["H", null, null, null, "E", null], frequency: 106 },
  { letters: [null, "U", "R", null, null, null], frequency: 105 },
  { letters: [null, "E", "R", null, null, null], frequency: 105 },
  { letters: ["R", null, null, null, "E", null], frequency: 105 },
];
